SET(SDL_TTF_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")

# Support both 32 and 64 bit builds
IF (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
    SET(SDL2_TTF_LIBRARIES_DIR "${CMAKE_CURRENT_LIST_DIR}/lib/x64")
ELSE ()
    SET(SDL2_TTF_LIBRARIES_DIR "${CMAKE_CURRENT_LIST_DIR}/lib/x86")
ENDIF ()

SET(SDL_TTF_LIBRARIES "${SDL2_TTF_LIBRARIES_DIR}/SDL2_ttf.lib")

